name: Build (Main)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'public/**'
      - '.github/workflows/pr-build.yml'
      - 'install/friendly-filenames.json'
      - 'Makefile'
      - 'index.html'
      - 'vite.config.ts'
      - '.npmrc'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  checkout-full-src:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21'

      - run: go version

      - name: Checkout dae latest
        uses: actions/checkout@v4
        with:
          repository: daeuniverse/dae
          ref: main
          submodules: 'recursive'
          fetch-depth: 0

      - name: Checkout dae-wing latest
        uses: actions/checkout@v4
        with:
          repository: daeuniverse/dae-wing
          ref: main
          path: dae-wing
          fetch-depth: 0

      - name: Download Go module dependencies
        run: |
          git submodule update --init --recursive
          export GOMODCACHE="${PWD}/go-mod"
          go mod download -modcacherw
          if [ -d "dae-core" ]; then
            cd dae-core && go mod download -modcacherw && cd ..
          fi
          find "$GOMODCACHE" -maxdepth 1 ! -name "cache" ! -name "go-mod" -exec rm -rf {} \;
          if [ -f Makefile ]; then
            sed -i 's/#export GOMODCACHE=$(PWD)\/go-mod/export GOMODCACHE=$(PWD)\/go-mod/' Makefile || true
          fi

      - name: Generate GraphQL resolver (only x86_64)
        if: runner.arch == 'X64'
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler gcc g++ make
          go install github.com/99designs/gqlgen@latest
          export PATH="$PATH:$(go env GOPATH)/bin"
          cd wing/graphql/service/config/global
          go generate ./...
          cd ../../../..

      - name: Create full source ZIP archive
        run: zip -9vr daed-full-src.zip . -x .git/\*

      - name: Upload artifact - full source
        uses: actions/upload-artifact@v4
        with:
          name: daed-full-src.zip
          path: daed-full-src.zip

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3.0.0
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest

      - name: Build Web UI
        run: |
          pnpm install
          pnpm build

      - name: Upload artifact - web
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: dist

  build-bundle:
    needs: [build-web]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
        include:
          - goos: linux
            goarch: amd64
            goamd64: v1
          - goos: linux
            goarch: amd64
            goamd64: v2
          - goos: linux
            goarch: amd64
            goamd64: v3

    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: |
          date=$(git log -1 --format="%cd" --date=short | sed 's/-//g')
          count=$(git rev-list --count HEAD)
          commit=$(git rev-parse --short HEAD)
          package_version="${date}r${count}${commit}"
          version="unstable-$package_version"
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$package_version" >> $GITHUB_ENV

      - name: Get Filename
        id: get_filename
        run: |
          export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOAMD64\"].friendlyName" -r < install/friendly-filenames.json)
          echo "BUNDLE_NAME=daed-$_NAME" >> $GITHUB_OUTPUT

      - name: Download Web Artifact
        uses: actions/download-artifact@v4
        with:
          name: web
          path: dist/

      - name: Build Binary Bundle (anytls enabled)
        run: |
          mkdir -p ./bundled/
          export VERSION=${{ steps.get_version.outputs.VERSION }}
          export GOFLAGS="-trimpath -modcacherw"
          export OUTPUT=bundled/${{ steps.get_filename.outputs.BUNDLE_NAME }}
          export ENABLE_ANYTLS=1
          make
          cp ./install/daed.service ./bundled/
          curl -L -o ./bundled/geoip.dat https://github.com/v2rayA/dist-v2ray-rules-dat/raw/master/geoip.dat
          curl -L -o ./bundled/geosite.dat https://github.com/v2rayA/dist-v2ray-rules-dat/raw/master/geosite.dat

      - name: Upload artifact - bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_filename.outputs.BUNDLE_NAME }}
          path: bundled/*

      - name: Build Linux Packages
        run: |
          sudo apt install -y libarchive-tools rpm
          sudo gem install fpm -v 1.15.1
          pushd bundled
          for package_manager in deb rpm; do
            package_arch="$GOARCH"
            fpm -s dir -t "$package_manager" -a $package_arch --version "${PACKAGE_VERSION}" \
              --url 'https://github.com/daeuniverse/dae' \
              --description "daed, A Modern Dashboard For dae." \
              --maintainer "daed@dae.v2raya.org" \
              --name daed --license 'MIT AGPL' \
              --package daed-linux-$GOARCH$GOAMD64.$package_manager \
              --after-install ../install/package_after_install.sh \
              --after-remove ../install/package_after_remove.sh \
              ./geoip.dat=/usr/share/daed/geoip.dat \
              ./geosite.dat=/usr/share/daed/geosite.dat \
              ./daed.service=/usr/lib/systemd/system/daed.service \
              ./${{ steps.get_filename.outputs.BUNDLE_NAME }}=/usr/bin/daed
          done
          popd || exit 1

      - name: Upload Linux packages
        uses: nanoufo/action-upload-artifacts-and-release-assets@v2.0
        with:
          path: |
            bundled/*.deb
            bundled/*.rpm
            bundled/*.pkg.tar.zst
